### PR TITLE
attempt to fix fmradio

### PR DESCRIPTION
**Pull request by shadowofleaf96**
this will fix 'dev/fm permission denied' error and make fmradio work but there no sound coming from the earpiece or speakers 
you need this modified framework/base to avoid force close

https://github.com/Shadowofleaf/android_frameworks_base/tree/lineage-17.1

### CODE REVIEW

**Comment by ADeadTrousers** [comment]
hi. Thanks for your work.
For the sound problem I think I have a pretty good guess:
According to this source code I found https://github.com/ADeadTrousers/android_packages_apps_FMRadio the app is relying on some other "special" audio libraries. As this is a rather old code (2010) I would not dare to integrate this into a current build. But as a example it's very helpful to get a look inside the whole framework and how the parts interact with each other. 
EDIT: In fact I found the hint with the missing audio files in another repo that features only the "jni" folder, but I forked this one because it includes the whole source repository.

As of including this into my repo I'm not convined yet as it's not fully working and I also have some questions:
In your previous mail you wrote that you've a Android 9 device so where did you get the Android 10 app from?
Where or how did you find the missing parts in framework_base? (Just curious and want to learn)
Personally I still want to get the LineageOS app working. How did you solve the permission problem? Only by relying on the stock apk/libraries? I want to understand how is it that the permission problem is solved by using another app that's basically working the same. All apps run in a special "user scope" and the permission is based on the underlying kernel.

If you can sort out the sound problems I'll include this PR.

**Comment by shadowofleaf96** [comment]
Yes indeed i have android 9 but i download stockrom for another phone that have helio p60 and support fm radio (genuis)

first that source of fm radio is so old that it need a java library (com.mediatek.fmradio.ext) that is obsolete is newest android (i didnt found any jar file related fm radio).

i discover that fmradio doesn’t need libfmcust anymore because it replaced by a config file (you will find in vendor/firmware) for me the best is to you use libfmcust library instead of the config cause it need some changes in my vendor to support.

yes you are right there is some special code added by mediatek to fix the permission things in the app not the jni libraries i did test it out a lot of time 

our last resort for open sourced app is to reverse engineering the app itself (it will take time and there is no easy solution to do it ) 

for the audio bug on fmradio i think it the missing code in libaudioclient as i did some digging i conclude that when building stockrom for mediatek phones there is a command in buildconfig.mk (AUDIO_MTK) that include all the things needed for the audio to be working you can see this source for reference 101.230.12.98:3333/BXProject/a6/frameworks/blob/master/av/media/libaudioclient/AudioSystem.cpp
It is simple to find the missing part that make the app force close , just use logcat and open the app (in my finding it said  symbol xunhu_intelligence is missing so i reverse engineer the app and i found that it reference to activity in the framework so i decompile framework.jar and get what i need , use apklab for visual studio it will help you a lot)
So that what i have now 
Im glad if i help you and im here if you found anything new


Regard 
SH

**Comment by ADeadTrousers** [comment]
Hi.

I found a better way to integrate XunhuOption.java > 607294ea508c0635dae17c279f20cf6c680dddd6
So you don't need to modify your own copy of android_frameworks_base.
As my device is already Android 10 I also don't need another FMRadio.apk from a different phone. So your pull request is more or less obsolete for me now.

I'm on the same page as you are now: Radio seems to be working but no sound neither from the headphones nor the speakers.

**Review by ADeadTrousers — COMMENTED** [review]
Except of the new dimen value "status_bar_height" nothing else can be applied because the Atom L/XL already are Android 10 devices so no blobs from other devices are necessary.

**Comment by Yorizuka** [comment]
Hello, this is unrelated to the Atom or this repo, but I don't see a better place to ask, Currently I am attempting to figure out how to add FM radio support to the Unihertz Jelly Star. Are you aware of anyone who was successful in doing so. And what would be the steps involved?
I have never worked with android, I am just a Linux power user that is way over his head and wanted to use the FM radio functionality. Maybe the best move is to give up, but I wanted to ask first.

The approach I tried was to extract the radio app APK out of the original android rom. Then using catlog and to solve issues until the app would work. I failed at getting the app to find `libfmjni.so`. placing it inside of the `/system/lib64` did not solve my issue, there is some sort of android specific white listing mechanism nightmare.
```
09-27 14:41:40.191 3863 3863 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libfmjni.so" needed or dlopened by "/apex/com.android.art/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
```
My attempt at fixing this issue was to make an edit to `/system/etc/public.libraries.txt` but that did nothing and just soft locked the device.

I was using magisk to add and replace system files.

**Comment by ADeadTrousers** [comment]
First of all: What ROM do you use?
I'm using Lineage and build it myself. Therefor it was rather easy for me to get it to work using the app that comes with the ROM.
The thing is, prior to A10, the FM radio app was able to access the fm device directly (through libfmjni.so). Starting with A10 a special service is required to do so. I can only speculate why this would be a good idea. Maybe it allows for more than one app to access the device or to only need to authorize one program in selinux to access the device. Who knows?
So in my ROM I changed everything back to the pre A10 era. I modified the access rights (ueventd.mt6771.rc), the selinux rules and reintroduced libfmcust.so.

**Comment by Yorizuka** [comment]
LineageOS20 but it was a device generic "GSI" build https://old.reddit.com/r/unihertz/comments/16sviga
We got it pre-built from here https://sourceforge.net/projects/andyyan-gsi/files/lineage-20-td/

**Comment by ADeadTrousers** [comment]
The stock rom places the libfmjni.so (that's relying on the service) in product.
The LineageOS app needs it in system. Also the LOS way of integrating FM radio uses libfmcust.so.
I don't think you can use the stock libfmjni.so and simply place it in system as all the selinux rules in vendor (where the service resides) point to product.
Therefor I think you need to use a prebuilt fmradio.apk, libfmjni.so, libfmcust.so, modify the fileaccess on fm_dev and modify the selinux rules accordingly. For libfmcust.so you could use mine as it features many different fm chips from mediatek. For the prebuilt portions and other modifications you best contact the GSI maintainer to include the LOS FM radio app. Also you'd might need to modify some code as the mediatek chipsets have a different conversion factor for the frequencies:
https://github.com/ADeadTrousers/android_device_Unihertz_Atom_LXL/blob/master/patch/packages_apps_FMRadio/0002-Set-conversion-factor-to-100.patch

**Pull request closed without merging**
